services:

  saptet:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      VERCEL_PROJECT_PRODUCTION_URL: saptet.taisaovayem.com